### ISSUE TITLE
Question about Number of Voxels used for CNN Feature Predictions

### ISSUE THREAD

**Issue by sreejank** [KamitaniLab/DeepImageReconstruction#1]
Hi,

Thanks a lot for sharing this code. It's really well-written and organized. I just had a question about Supplementary Figure 4 in your preprint, where you run this pipeline on the Generic Object Decoding dataset (https://github.com/KamitaniLab/GenericObjectDecoding/). The number of voxels used for Sparse Linear Regression in the VC ROI was 1000, but the preprint says 500 voxels. Did you use 1000 voxels for Supplementary Figure 4 or 500 voxels?

Thanks!

**Comment by shen-gh** [comment]
We used 500 voxels for VC in the reconstruction study.

**Comment by sreejank** [comment]
Thanks!
