### ISSUE TITLE
original fmri

### ISSUE THREAD

**Issue by kingjr** [KamitaniLab/DeepImageReconstruction#4]
Hi, 

Is there a way to download the original fMRI data and the corresponding stimulus condition?

Thank you!

**Comment by ShuntaroAoki** [comment]
Hi,

Raw fMRI data are available at OpenNeuro (https://openneuro.org/datasets/ds001506). You can request the stimulus images via https://forms.gle/ujvA34948Xg49jdn9.
Hope these help you.

**Comment by kingjr** [comment]
Perfect, thanks!
