### ISSUE TITLE
structure of voxel data

### ISSUE THREAD

**Issue by alexhalpin** [KamitaniLab/DeepImageReconstruction#9]
Hello,
I am trying to parse the processed fMRI data but do not understand the structure of the data. 

I understand from your paper that the first dimension is the data point (for example, imagery.shape[0] = 20 * 26). 

However, I do not understand the significance of the second dimension (11729, 11730, 11117, 11118, 9922, 9923). 

Is this just the number of voxels? Does this vector need to be reshaped to represent a 2D or 3D matrix? How did you go about feeding this into the VGG19? And why is the natural image data 1 dimension larger?

Thank you very much for your time and please forgive my naivety.

<img width="608" alt="Screen Shot 2022-11-28 at 7 08 42 PM" src="https://user-images.githubusercontent.com/88046770/204406892-016e4dc7-a4dd-4958-a98f-1bd1cd670f83.png">

**Comment by ShuntaroAoki** [comment]
The fMRI voxel data (*.h5 files) are saved in our lab's custom format.
You can extract data with our Python package https://github.com/KamitaniLab/bdpy.

```shell-session
pip install bdpy
```

Then

```python
import bdpy

bdata = bdpy.BData('path/to/sub-01_perceptionNaturalImageTest_original_VC.h5')
fmri_v1 = bdata.select('ROI_V1')  # Voxel data in V1 as a sample-by-voxel array
```

The following ROIs are included:

- ROI_V1
- ROI_V2
- ROI_V3
- ROI_V4
- ROI_LOC
- ROI_FFA
- ROI_PPA
- ROI_LVC
- ROI_HVC
- ROI_VC

Similarly you can extract stimulus labels and experiment information from the `bdata`.

```python
image_index = bdata.select('image_index')  # Index of stimulus images for each sample
runs = bdata.select('Run')  # Run numbers for each sample
```

**Comment by alexhalpin** [comment]
Ah! I see. Thank you so much for your help!
